GET http://localhost:4000/api/activities

###

GET http://localhost:4000/api/activities/60ab8414cdda4cd0345fb75c

###

POST http://localhost:4000/api/activities
content-type: application/json

{
  "number": 6,
    "country": "fake country",
    "activity": "fake activity",
    "season": "fake season",
    "name": "fake name",
    "image_url": "fake url",
    "description": "a test place"
}

###

PUT http://localhost:4000/api/activities/60ab8a499e254ad5faba2673
content-type: application/json

{
  "number": 6,
    "country": "fake country 2",
    "activity": "fake activity",
    "season": "fake season",
    "name": "fake name",
    "image_url": "fake url",
    "description": "a test place"
}

###

DELETE http://localhost:4000/api/activities/60ab8a499e254ad5faba2673

