GET http://localhost:4000/api/activities

###
GET http://localhost:4000/api/activities/60ab8414cdda4cd0345fb75c

###

GET http://localhost:4000/api/activities/search?season=Summer

###

POST http://localhost:4000/api/activities
content-type: application/json
Authorization: Bearer 

{
  "number": 6,
    "country": "fake country",
    "activity": "fake activity",
    "season": "fake season",
    "name": "fake name",
    "image_url": "fake url",
    "description": "a test place"
}

### 
PUT http://localhost:4000/api/activities/60ab852620a9511f057a8515
content-type: application/json

{
  "number": 1,
    "country": "fake country",
    "activity": "fake activity",
    "season": "fake season",
    "name": "fake name",
    "image_url": "fake url",
    "description": "a test place"
}

###

DELETE http://localhost:4000/api/activities/60ab91ff66f4f02a4012042a

###

//USERS

POST http://localhost:4000/api/register
content-type: application/json

{
  "username": "Jack" ,
  "password": "jackpass",
  "passwordConfirmation": "jackpass",
  "email": "jack@email"
}

###

POST http://localhost:4000/api/login
content-type: application/json 

{
  "password": "jackpass",
  "email": "jack@email"
}

